/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BasicForm: typeof import('./src/components/common/BasicForm/src/BasicForm.vue')['default']
    CellRender: typeof import('./src/components/common/VTable/src/components/cellRender.vue')['default']
    Checkbox: typeof import('./src/components/common/BasicForm/src/components/Checkbox.vue')['default']
    EButton: typeof import('./src/components/common/EButton/src/EButton.vue')['default']
    FormAction: typeof import('./src/components/common/BasicForm/src/components/FormAction.vue')['default']
    FormItem: typeof import('./src/components/common/BasicForm/src/components/FormItem.vue')['default']
    InitPage: typeof import('./src/components/common/InitPage/src/InitPage.vue')['default']
    Input: typeof import('./src/components/form/components/Input/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/common/VTable/src/components/searchForm/index.vue')['default']
    Select: typeof import('./src/components/common/BasicForm/src/components/Select.vue')['default']
    SlotRender: typeof import('./src/components/common/BasicForm/src/components/slotRender.vue')['default']
    VTable: typeof import('./src/components/common/VTable/src/VTable.vue')['default']
    VxeColumn: typeof import('vxe-table/es/column/index.js')['VxeColumn']
    VxeTable: typeof import('vxe-table/es/table/index.js')['VxeTable']
  }
}
