/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Input: typeof import('./src/components/form/components/Input/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VTable: typeof import('./src/components/common/VTable/index.vue')['default']
    VxeColumn: typeof import('vxe-table/es/column/index.js')['VxeColumn']
    VxeTable: typeof import('vxe-table/es/table/index.js')['VxeTable']
  }
}
